### ISSUE TITLE
Demo times out on redirect to /oauth/authorize

### ISSUE THREAD

**Issue by swdove** [14gasher/oauth-example#10]
I'm trying to test the demo to understand the flow - the /oauth form submission passes values into the server but the server process never resolves and the redirect to /oauth/authorize eventually times out. This is the final output of the dev server:

![Screen Shot 2019-11-19 at 2 33 28 PM](https://user-images.githubusercontent.com/16566773/69188462-d4a53800-0ad9-11ea-9166-4989af211b66.png)

All but 3 of the included tests are also failing due to timeouts or 400s. 

Any help would be appreciated!

**Comment by swdove** [comment]
Disregard! I missed the comment about updating the underlying oauth2-server library. Thank you for your work, this is very helpful!

**Comment by ratnadeepkedar** [comment]
@swdove I am facing the same issue, can you please explain to me how to fix it? What does this mean - I missed the comment about updating the underlying oauth2-server library.

**Comment by swdove** [comment]
@ratnadeepkedar There is a note in the model.js of this project that says the generateAuthorizationCode method in the oauth2-server library (which is a dependency of express-oauth-server) needs to be updated to return an object instead of a promise.

Instructions start at line 113 here: https://github.com/14gasher/oauth-example/blob/master/auth/oauth/model.js

Making this change fixed the timeout issue for me.

**Comment by ratnadeepkedar** [comment]
Thank you @swdove  for the quick response. It also fixed for me. :)
