### ISSUE TITLE
solved bugs in your code

### ISSUE THREAD

**Issue by suryateja648** [14gasher/oauth-example#12]
I solved the bugs in your code according to the new latest version. how to give push requests to your repo.

**Comment by Zireael** [comment]
Click to Fork and then Create pull request from your fork

**Comment by Zireael** [comment]
![image](https://user-images.githubusercontent.com/3856578/82114713-5bb82d80-9756-11ea-855e-8f387996f2ef.png)

then
![image](https://user-images.githubusercontent.com/3856578/82114720-65419580-9756-11ea-8a34-fb2e713b0879.png)

then
![image](https://user-images.githubusercontent.com/3856578/82114730-6ecafd80-9756-11ea-9253-623eeb379d58.png)

You can edit more than one file in your fork, and then submit pull request with all of them at one time.
