### ISSUE TITLE
Add Authorization landing page example

### ISSUE THREAD

**Issue by ghost** [14gasher/oauth-example#4]
Firstly, I just want to say thank you for your hard and sharing this with us. It's helped me understand the flow of using authorization codes in node-oauth2-server a lot better than the official documentation.

I was wondering whether you would be open to the idea of adding an example of how to implement an authorization landing page, where the user is prompted to make a decision on whether or not to grant the client's request.

Much appreciated.

**Comment by 14gasher** [comment]
That's an awesome idea.

I'm planning on updating this some more this week, so I'll look into that as well.

**Comment by 14gasher** [comment]
A client landing page for users to grant access to the auth server is now implemented. 

Hope that helps @Tyncture
